"""Export channel lists to markdown and plain-text files."""

from __future__ import annotations

import os
from datetime import UTC, datetime
from pathlib import Path

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from telecrime.channels.service import build_subscription_query
from telecrime.models import TelegramChannel


def _tme_url(ch: TelegramChannel) -> str:
    if ch.username:
        return f"https://t.me/{ch.username}"
    if ch.invite_link:
        return ch.invite_link
    return ""


def _fmt(n: int | None) -> str:
    if n is None:
        return "-"
    return f"{n:,}"


def _archive_counts_by_platform_id(session: Session) -> dict[int, int]:
    """Return {platform_id: archive_count} for all conversations that have attachments."""
    from telecrime.models import Conversation, FileAttachment, Message

    rows = session.execute(
        select(Conversation.platform_id, func.count(FileAttachment.id))
        .join(Message, Message.conversation_id == Conversation.id)
        .join(FileAttachment, FileAttachment.message_id == Message.id)
        .where(Conversation.platform_id.isnot(None))
        .group_by(Conversation.platform_id)
    ).all()
    return {platform_id: count for platform_id, count in rows}


def generate_markdown(session: Session) -> str:
    """Build the full markdown report string."""
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    # Subscribed channels ordered by credentials extracted. Only active and
    # accessible ones are listed — deleted/private channels stay out of the
    # public list.
    subscribed = (
        session.query(TelegramChannel)
        .filter(
            TelegramChannel.is_subscribed.is_(True),
            TelegramChannel.is_active.is_(True),
            TelegramChannel.is_accessible.is_(True),
        )
        .order_by(TelegramChannel.credentials_extracted.desc().nulls_last())
        .all()
    )

    # Candidate channels (active, accessible, criteria-matching, not yet subscribed)
    candidates = (
        build_subscription_query(session, stealer_only=True)
        .order_by(TelegramChannel.member_count.desc().nulls_last())
        .limit(100)
        .all()
    )

    archive_counts = _archive_counts_by_platform_id(session)

    total_creds = sum(ch.credentials_extracted or 0 for ch in subscribed)
    total_archives = sum(
        archive_counts.get(ch.platform_id, 0) for ch in subscribed if ch.platform_id is not None
    )

    lines: list[str] = []
    lines.append("# Telecrime — Channel List")
    lines.append("")
    lines.append(f"*Generated: {now}*")
    lines.append("")
    lines.append(
        f"**Subscribed:** {len(subscribed)} &nbsp;|&nbsp; "
        f"**Credentials extracted:** {total_creds:,} &nbsp;|&nbsp; "
        f"**Archives processed:** {total_archives:,}"
    )
    lines.append("")

    # --- Subscribed channels ---
    lines.append("## Subscribed channels")
    lines.append("")
    lines.append(
        "| Channel | URL | Members | Credentials | Archives | Messages | Last active |"
    )
    lines.append("|---------|-----|--------:|------------:|--------:|--------:|-------------|")

    for ch in subscribed:
        url = _tme_url(ch)
        url_cell = f"[link]({url})" if url else "-"
        archives = archive_counts.get(ch.platform_id, 0) if ch.platform_id else 0
        lines.append(
            f"| {ch.title or ch.username or '-'} "
            f"| {url_cell} "
            f"| {_fmt(ch.member_count)} "
            f"| {_fmt(ch.credentials_extracted)} "
            f"| {_fmt(archives) if archives else '-'} "
            f"| {_fmt(ch.messages_seen)} "
            f"| {ch.last_checked.strftime('%Y-%m-%d') if ch.last_checked else '-'} |"
        )

    lines.append("")

    # --- Candidate channels ---
    if candidates:
        lines.append("## Candidate channels (not yet subscribed)")
        lines.append("")
        lines.append("Channels matching stealer-log criteria that are active and accessible.")
        lines.append("")
        lines.append("| Channel | URL | Members | Discovered |")
        lines.append("|---------|-----|--------:|------------|")
        for ch in candidates:
            url = _tme_url(ch)
            url_cell = f"[link]({url})" if url else "-"
            disc = ch.discovered_at.strftime("%Y-%m-%d") if ch.discovered_at else "-"
            lines.append(
                f"| {ch.title or ch.username or '-'} "
                f"| {url_cell} "
                f"| {_fmt(ch.member_count)} "
                f"| {disc} |"
            )
        lines.append("")

    lines.append("---")
    repo_url = os.environ.get("TELECRIME_REPO_URL")
    if repo_url:
        lines.append(f"*Auto-generated by [telecrime]({repo_url})*")
    else:
        lines.append("*Auto-generated by telecrime*")
    lines.append("")

    return "\n".join(lines)


def generate_txt(session: Session) -> str:
    """Build the plain-text list of all active channels (one URL per line).

    Only channels that are both active AND accessible are included: a channel
    with ``is_active=False`` was reported as deleted/not-found by Telegram, and
    one with ``is_accessible=False`` is private, banned, or otherwise
    unreachable — neither belongs in a public list.
    """
    channels = (
        session.query(TelegramChannel)
        .filter(
            TelegramChannel.is_active.is_(True),
            TelegramChannel.is_accessible.is_(True),
            TelegramChannel.username.isnot(None),
        )
        .order_by(func.lower(TelegramChannel.username))
        .all()
    )
    return "\n".join(f"https://t.me/{ch.username}" for ch in channels) + "\n"


def export_reports(session: Session, output_dir: Path) -> tuple[Path, Path]:
    """Write channels.md and channels.txt to output_dir. Returns the two paths."""
    output_dir.mkdir(parents=True, exist_ok=True)

    md_path = output_dir / "channels.md"
    txt_path = output_dir / "channels.txt"

    md_path.write_text(generate_markdown(session), encoding="utf-8")
    txt_path.write_text(generate_txt(session), encoding="utf-8")

    return md_path, txt_path
