"""Add message metadata fields

Revision ID: 05fc44e0c2ea
Revises: 09272cbc5bde
Create Date: 2026-01-22 07:07:56.067310
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05fc44e0c2ea'
down_revision: Union[str, None] = '09272cbc5bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('forwards', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('edit_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('post_author', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('grouped_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'grouped_id')
    op.drop_column('messages', 'post_author')
    op.drop_column('messages', 'edit_date')
    op.drop_column('messages', 'forwards')
    op.drop_column('messages', 'views')
    # ### end Alembic commands ###
