"""Add ParsedCredential table

Revision ID: 09272cbc5bde
Revises: 4a5ecdd6d8fb
Create Date: 2026-01-21 21:35:53.559441
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09272cbc5bde'
down_revision: Union[str, None] = '4a5ecdd6d8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email_domain', sa.String(length=255), nullable=True),
    sa.Column('application', sa.String(length=100), nullable=True),
    sa.Column('profile', sa.String(length=100), nullable=True),
    sa.Column('extraction_job_id', sa.Integer(), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('source_archive', sa.String(length=512), nullable=True),
    sa.Column('source_conversation_id', sa.Integer(), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('stealer_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_job_id'], ['extraction_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_credentials_domain'), 'parsed_credentials', ['domain'], unique=False)
    op.create_index(op.f('ix_parsed_credentials_email_domain'), 'parsed_credentials', ['email_domain'], unique=False)
    op.create_index(op.f('ix_parsed_credentials_extraction_job_id'), 'parsed_credentials', ['extraction_job_id'], unique=False)
    op.create_index(op.f('ix_parsed_credentials_source_conversation_id'), 'parsed_credentials', ['source_conversation_id'], unique=False)
    op.create_index(op.f('ix_parsed_credentials_url'), 'parsed_credentials', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_credentials_url'), table_name='parsed_credentials')
    op.drop_index(op.f('ix_parsed_credentials_source_conversation_id'), table_name='parsed_credentials')
    op.drop_index(op.f('ix_parsed_credentials_extraction_job_id'), table_name='parsed_credentials')
    op.drop_index(op.f('ix_parsed_credentials_email_domain'), table_name='parsed_credentials')
    op.drop_index(op.f('ix_parsed_credentials_domain'), table_name='parsed_credentials')
    op.drop_table('parsed_credentials')
    # ### end Alembic commands ###
