"""Initial schema

Revision ID: 4a5ecdd6d8fb
Revises: 
Create Date: 2026-01-21 09:08:57.472525
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5ecdd6d8fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('base_name', sa.String(length=255), nullable=True),
    sa.Column('expected_part_count', sa.Integer(), nullable=False),
    sa.Column('detected_part_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INCOMPLETE', 'READY', 'EXTRACTING', 'EXTRACTED', 'CLEANED', 'FAILED', 'FAILED_TERMINAL', name='groupstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_groups_fingerprint'), 'archive_groups', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_archive_groups_status'), 'archive_groups', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_id', sa.BigInteger(), nullable=False),
    sa.Column('access_hash', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('conversation_type', sa.String(length=50), nullable=False),
    sa.Column('is_member', sa.Boolean(), nullable=False),
    sa.Column('is_accessible', sa.Boolean(), nullable=False),
    sa.Column('join_attempted', sa.Boolean(), nullable=False),
    sa.Column('join_succeeded', sa.Boolean(), nullable=True),
    sa.Column('last_ingested_message_id', sa.BigInteger(), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_platform_id'), 'conversations', ['platform_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.BigInteger(), nullable=False),
    sa.Column('platform_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('is_forwarded', sa.Boolean(), nullable=False),
    sa.Column('forwarded_from_id', sa.BigInteger(), nullable=True),
    sa.Column('forwarded_from_name', sa.String(length=255), nullable=True),
    sa.Column('forwarded_message_id', sa.BigInteger(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_is_processed'), 'messages', ['is_processed'], unique=False)
    op.create_index(op.f('ix_messages_platform_id'), 'messages', ['platform_id'], unique=False)
    op.create_index(op.f('ix_messages_platform_timestamp'), 'messages', ['platform_timestamp'], unique=False)
    op.create_table('file_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('platform_file_id', sa.String(length=255), nullable=False),
    sa.Column('platform_file_unique_id', sa.String(length=255), nullable=True),
    sa.Column('access_hash', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('is_archive_candidate', sa.Boolean(), nullable=False),
    sa.Column('archive_type', sa.String(length=50), nullable=True),
    sa.Column('detected_part_number', sa.Integer(), nullable=True),
    sa.Column('detected_base_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_attachments_is_archive_candidate'), 'file_attachments', ['is_archive_candidate'], unique=False)
    op.create_index(op.f('ix_file_attachments_message_id'), 'file_attachments', ['message_id'], unique=False)
    op.create_index(op.f('ix_file_attachments_platform_file_id'), 'file_attachments', ['platform_file_id'], unique=False)
    op.create_table('first_seen_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('first_seen_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_conversation_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_message_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_message_platform_id', sa.BigInteger(), nullable=True),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['first_seen_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_seen_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_first_seen_index_content_hash'), 'first_seen_index', ['content_hash'], unique=True)
    op.create_index(op.f('ix_first_seen_index_first_seen_timestamp'), 'first_seen_index', ['first_seen_timestamp'], unique=False)
    op.create_table('password_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.Enum('MESSAGE', 'NEARBY', 'CONVERSATION', 'LEARNED', 'GLOBAL', name='passwordscope'), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('context_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('times_succeeded', sa.Integer(), nullable=False),
    sa.Column('times_failed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_candidates_conversation_id'), 'password_candidates', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_password_candidates_scope'), 'password_candidates', ['scope'], unique=False)
    op.create_index(op.f('ix_password_candidates_source_message_id'), 'password_candidates', ['source_message_id'], unique=False)
    op.create_table('download_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('temp_path', sa.String(length=1024), nullable=True),
    sa.Column('verified_size', sa.BigInteger(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DOWNLOADING', 'COMPLETED', 'FAILED', 'FAILED_TERMINAL', name='downloadstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['file_attachments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_artifacts_attachment_id'), 'download_artifacts', ['attachment_id'], unique=True)
    op.create_index(op.f('ix_download_artifacts_content_hash'), 'download_artifacts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_download_artifacts_status'), 'download_artifacts', ['status'], unique=False)
    op.create_table('extraction_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'PASSWORD_NEEDED', 'COMPLETED', 'FAILED', 'FAILED_TERMINAL', name='extractionstatus'), nullable=False),
    sa.Column('used_password_id', sa.Integer(), nullable=True),
    sa.Column('password_attempts', sa.Integer(), nullable=False),
    sa.Column('extractor_name', sa.String(length=50), nullable=False),
    sa.Column('extractor_version', sa.String(length=50), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=50), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('target_extensions', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['archive_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_password_id'], ['password_candidates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_jobs_group_id'), 'extraction_jobs', ['group_id'], unique=False)
    op.create_index(op.f('ix_extraction_jobs_status'), 'extraction_jobs', ['status'], unique=False)
    op.create_table('archive_group_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('part_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['download_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['archive_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_group_parts_artifact_id'), 'archive_group_parts', ['artifact_id'], unique=True)
    op.create_index(op.f('ix_archive_group_parts_group_id'), 'archive_group_parts', ['group_id'], unique=False)
    op.create_table('extracted_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('output_path', sa.String(length=1024), nullable=False),
    sa.Column('output_filename', sa.String(length=255), nullable=False),
    sa.Column('output_type', sa.String(length=50), nullable=True),
    sa.Column('output_size', sa.Integer(), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('source_conversation_id', sa.Integer(), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_outputs_job_id'), 'extracted_outputs', ['job_id'], unique=False)
    op.create_index(op.f('ix_extracted_outputs_output_hash'), 'extracted_outputs', ['output_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_outputs_output_hash'), table_name='extracted_outputs')
    op.drop_index(op.f('ix_extracted_outputs_job_id'), table_name='extracted_outputs')
    op.drop_table('extracted_outputs')
    op.drop_index(op.f('ix_archive_group_parts_group_id'), table_name='archive_group_parts')
    op.drop_index(op.f('ix_archive_group_parts_artifact_id'), table_name='archive_group_parts')
    op.drop_table('archive_group_parts')
    op.drop_index(op.f('ix_extraction_jobs_status'), table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_group_id'), table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    op.drop_index(op.f('ix_download_artifacts_status'), table_name='download_artifacts')
    op.drop_index(op.f('ix_download_artifacts_content_hash'), table_name='download_artifacts')
    op.drop_index(op.f('ix_download_artifacts_attachment_id'), table_name='download_artifacts')
    op.drop_table('download_artifacts')
    op.drop_index(op.f('ix_password_candidates_source_message_id'), table_name='password_candidates')
    op.drop_index(op.f('ix_password_candidates_scope'), table_name='password_candidates')
    op.drop_index(op.f('ix_password_candidates_conversation_id'), table_name='password_candidates')
    op.drop_table('password_candidates')
    op.drop_index(op.f('ix_first_seen_index_first_seen_timestamp'), table_name='first_seen_index')
    op.drop_index(op.f('ix_first_seen_index_content_hash'), table_name='first_seen_index')
    op.drop_table('first_seen_index')
    op.drop_index(op.f('ix_file_attachments_platform_file_id'), table_name='file_attachments')
    op.drop_index(op.f('ix_file_attachments_message_id'), table_name='file_attachments')
    op.drop_index(op.f('ix_file_attachments_is_archive_candidate'), table_name='file_attachments')
    op.drop_table('file_attachments')
    op.drop_index(op.f('ix_messages_platform_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_platform_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_processed'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_platform_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_archive_groups_status'), table_name='archive_groups')
    op.drop_index(op.f('ix_archive_groups_fingerprint'), table_name='archive_groups')
    op.drop_table('archive_groups')
    # ### end Alembic commands ###
